### ISSUE TITLE
Cant compile the file

### ISSUE THREAD

**Issue by fredsmil111** [cookgreen/BF1BotMod#3]
![image](https://github.com/user-attachments/assets/6018da5e-f735-4c18-bca4-f3bf1d841f00)

**Comment by cookgreen** [comment]
why do you use the VSCode? please use ths Visual Studio!

**Comment by fredsmil111** [comment]
> why do you use the VSCode? please use ths Visual Studio!

Thanks i compile and launch the injoctor but it's closing when I start it...

**Comment by fredsmil111** [comment]
I mean I launch the BF1 and then injector but it's closing momentaly... it's do nothing just open and closing....
